version: '3.8'

services:
  db:
    image: postgres:14
    container_name: mangafocal-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - backend

  test-db:
    image: postgres:14
    container_name: mangafocal-db-test
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - backend

networks:
  backend: